Makefile
azure/azure-release-pipeline.yml
manifest_template.yml

Apm 1936 deploy to internal dev sandbox

---

manifest_template.yml

APM-1936 Add external sandbox environment

---

.gitignore

apm-1926: extra gitignore to test pr

---

azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml
azure/templates/run-smoke-tests.yml
tests/api_tests.py

apm-1936: rename smoke tests

---

specification/components/examples/Immunization.json
specification/components/schemas/Bundle.yaml
specification/components/schemas/Immunization.yaml
specification/components/schemas/Patient.yaml
specification/immunisation-history.yaml

Apm 1933 oas endpoint

---

proxies/live/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml

apm-1926: immunisation history target real endpoint in healthcheck

---

sandbox/handlers.js
sandbox/responses/empty-bundle-response.json

APM-1936 add emptyBundle response

---

sandbox/app.js
sandbox/handlers.js

APM-1936 changing s to z

---

proxies/live/apiproxy/targets/ih-target.xml

apm-1926: temporarily disable apikey -> quota vars

---

proxies/live/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml
sandbox/responses/get-imm-response.json

apm-1926: update bundle and use _status for healthcheck

---

manifest_template.yml
proxies/live/apiproxy/policies/AssignMessage.SetAccessModeApplicationRestricted.xml
proxies/live/apiproxy/targets/ih-target.xml

APM-1942 adding application restricted

---

azure/azure-build-pipeline.yml

Use cache task in build pipeline

APM-1978 Add cache_steps to build pipeline

---

azure/azure-build-pipeline.yml

Remove unnecessary alias inputs

Apm 1978 remove alias

---

azure/templates/run-smoke-tests.yml

Apm 1978 cache smoketest dependancies

---

poetry.lock
pyproject.toml
tests/api_tests.py
tests/conftest.py

apm-1946: slimline e2e tests

---

tests/api_tests.py

apm-1946: increase wait for status

---

manifest_template.yml
proxies/live/apiproxy/policies/OAuthV2.VerifyAccessToken.xml

Restrict to app-restricted only

APM-1162 Fix allowed scopes

---

manifest_template.yml
tests/api_tests.py

Set 3500tps limits.
A note to the reviews: 60*3500 = 210000

APM-1995 Change quota/ratelimit to 3500tps

---

tests/api_tests.py

APM-1943 Add sleep to other tests to stop flakey results

---

manifest_template.yml

APM-1995 Raise ratelimit and quota in int

---

proxies/live/apiproxy/policies/AssignMessage.CatchAllJWTError.xml
proxies/live/apiproxy/policies/AssignMessage.NoMatchingPublicKey.xml
proxies/live/apiproxy/targets/ih-target.xml
tests/api_tests.py

* Catch No matching public Key error

APM-1943 Add no matching public key error

---

tests/api_tests.py

APM-1943 fix number typo

---

proxies/live/apiproxy/policies/AssignMessage.JWKS.xml
proxies/live/apiproxy/policies/DecodeJWT.FromExternalIdToken.xml
proxies/live/apiproxy/policies/DecodeJWT.FromNHSDUserIdentityHeader.xml
proxies/live/apiproxy/policies/JavaScript.ValidateClaimFromExternalIdToken.xml
proxies/live/apiproxy/policies/LookupCache.JWKS.xml
proxies/live/apiproxy/policies/PopulateCache.JWKS.xml
proxies/live/apiproxy/policies/VerifyJWT.FromExternalIdToken.xml
proxies/live/apiproxy/resources/jsc/validate-claim-external-id-token.js
proxies/live/apiproxy/targets/ih-target.xml

APM-1943 Add caching policies

---

postman/immunisation-history-sandbox.postman_collection.json
sandbox/handlers.js
specification/immunisation-history.yaml

* Add initial sandbox postman collection 

APM-1954 Add postman collection

---

tests/conftest.py

Fixes tests by adding in required params to id token payloads generated for testing.

APM-1162 Add new id token headers

---

azure/azure-release-pipeline.yml

mm: deploy to dev environment too

---

manifest_template.yml

also need to add environment to the manifest

---

manifest_template.yml

Accidental short branch. Reducing rate limit back to 5tps on int

APM-2043 Reduce int rate limit back to 5tps

---

specification/components/examples/Immunization.json
specification/components/schemas/Immunization.yaml

Apm 2067   spec   remove "not done"

---

azure/azure-build-pipeline.yml

APM-2016 temp fix caching

---

manifest_template.yml
poetry.lock
proxies/live/apiproxy/policies/AssignMessage.AddUserIdHeader.xml
proxies/live/apiproxy/policies/AssignMessage.SetAccessModeApplicationRestricted.xml
proxies/live/apiproxy/policies/DecodeJWT.FromAccessToken.xml
proxies/live/apiproxy/policies/OAuthV2.VerifyAccessToken.xml
proxies/live/apiproxy/targets/ih-target.xml
pyproject.toml
tests/api_tests.py
tests/conftest.py

* Implement Token Exchange
* Add tests for token exchange flow

APM-2068 Token Exchange Integration

---

specification/immunisation-history.yaml

APM-2069 spec changes re. NHS login integration

---

proxies/live/apiproxy/targets/ih-target.xml

apm-251 upped keep alive

---

.gitignore
manifest_template.yml

* toggle on manual approval for prod

APM-2016-make-prod-manual-approval

---

proxies/live/apiproxy/policies/OAuthV2.VerifyAccessToken.xml
tests/api_tests.py
tests/conftest.py

apm-302: test enable token exchange

---

specification/immunisation-history.yaml

Added service level to spec

---

specification/immunisation-history.yaml

This change adds a link to the test test data pack page, and also removes a para that suggests there is only on test record in INT.

APM-2643 Update immunisation-history.yaml to reference new test data pack

---

specification/immunisation-history.yaml

fix broken link on valid NHS number

---

specification/immunisation-history.yaml

Updated security documentation

---

sandbox/fhir-responses/covid-immunization.fhir.js
sandbox/fhir-responses/hpv-immunization.fhir.js

DALA-1000 fixed sandbox statusReason output

---

proxies/live/apiproxy/policies/AssignMessage.PopulateAuthorisedTargetsFromApp.xml
proxies/live/apiproxy/policies/Javascript.PopulateAuthorisedTargetsFromApp.xml
proxies/live/apiproxy/resources/jsc/AuthorisedTargets.PopulateFromApp.js
proxies/live/apiproxy/targets/ih-target.xml
tests/api_tests.py

[DALA-1042] Consume authorised_targets as array

---

tests/api_tests.py

DALA-1017 added custom correlation id for each test

---

specification/immunisation-history.yaml

[DALA-1113] Remove date_range bullet point

---

proxies/live/apiproxy/policies/AssignMessage.AddRequestUrl.xml
proxies/live/apiproxy/policies/Javascript.PopulateRequestUrlHeader.xml
proxies/live/apiproxy/resources/jsc/RequestUrl.SetInHeader.js
proxies/live/apiproxy/targets/ih-target.xml

Add Request Url as header

---

proxies/live/apiproxy/policies/RaiseFault.AuthorisedTargetsAlreadyInHeader.xml
proxies/live/apiproxy/policies/RaiseFault.MissingAuthorisedTargets.xml
proxies/live/apiproxy/policies/RaiseFault.MissingNHSDUserIdentity.xml
tests/api_tests.py

[DALA-1039] Added error messages to response payload

---

azure/azure-release-pipeline.yml

[DALA-1141] enable prod producer approval

---

.github/workflows/continuous-integration.yml
tests/conftest.py

* :warning: Remove **nodejs** from Build step
Remove node from build step, see...
https://nhsdigital-platforms.slack.com/archives/C016JRWN6AY/p1670947616792619

Remove node from build step and fix failing tests

---

specification/immunisation-history.yaml

DMS-1194 Change spec to include Flu and HPV
